parameters:
#    phpist_index.example.class: phpist\IndexBundle\Example

services:
#    phpist_index.example:
#        class: %phpist_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
